### ISSUE TITLE
Fights doesn't count draws

### ISSUE THREAD

**Issue by Nigel-Brown** [andrew-couch/Tidy-Tuesday#4]
```
df %>% 
        select(fighter, height = Height_cms, reach = Reach_cms, Stance, age, wins, losses) %>% 
        filter(fighter == input$v_fighter_desc) %>% 
        rename_all(~str_replace(.x, "_", " ") %>% str_to_title) %>% 
        mutate(Fights = Wins + Losses) %>% 
        filter(Fights == max(Fights)) 
```
This code will return 2 fights for Aaron Philips when he has had 3 fights one of which was a draw.

**Comment by andrew-couch** [comment]
Hi, I'm not sure which script you are referring to since I do not have height, reach, or stance in my data. I believe I have converted ties to losses but a fighter's metrics are determined by both the fighter and his/her weight class. So if a fighter fought at a different weight class the metrics are recomputed to only fights in the weight class which may be the reason why Aaron Philips had a different number of fights since he has fought in both bantamweight and featherweight.

**Comment by Nigel-Brown** [comment]
I'm looking at the https://github.com/andrew-couch/Tidy-Tuesday/blob/master/Season%201/Apps/TidyTuesdayDashboardLevels/advanced_app.R code and the code for the fighter_desc table. The issue is that draws are not recorded as losses as far as I can see 
fighter        height reach Stance     age  wins losses
  <chr>           <dbl> <dbl> <chr>    <dbl> <dbl>  <dbl>
1 Aaron Phillips   175.  180. Southpaw    25     0      1
2 Aaron Phillips   175.  180. Southpaw    30     0      2
3 Aaron Phillips   175.  180. Southpaw    24     0      0
I changed the code to the following:
````
DT::datatable(ufc_df %>%
       filter(fighter == input$v_fighter_2 & weight_class == input$v_weight_class_3) %>%
       group_by('height cm' = Height_cms, 'reach cm' = Reach_cms, stance = Stance, 'age last fight' = age, wins, losses) %>%
      summarise(tmp = n()) %>%
      mutate(fights = wins + losses + tmp) %>%
      ungroup() %>%
      filter(fights == max(fights)) %>%
      select(-tmp),
      options = list(paging = FALSE,
                     searching = FALSE),
      rownames= FALSE)
```

**Comment by andrew-couch** [comment]
Ah I see, I'll make the changes later this afternoon. I noticed that the advanced_dashboard_helper.Rdata appears to be missing some fights so I'll have to adjust the dataset.
